[package]
name = "rust-xmlrpc"
version = "0.0.2"
authors = ["Galen Clark Haynes <gch@users.noreply.github.com>"]

[lib]
name = "xmlrpc"
path = "src/lib.rs"

[dependencies]
rustc-serialize = "0.2.7"
# hyper = 0.0.17 # FIXME

[[example]]
name = "simple"
path = "examples/simple.rs"

